name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Python
      uses: actions/setup-python@v4.2.0
      with:
        # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
        python-version: 3.8
        cache: pip
    
    - name: Install PIL
      run: pip install pillow
    
    - name: Setup WLA-DX
      run: |
        git clone https://github.com/vhelin/wla-dx # Clone the repository
        cd wla-dx
        mkdir build && cd build # Create building directory
        cmake .. # Generate build system
        cmake --build . --config Release # Build it
        cmake -P cmake_install.cmake
        cd ../..
      
    - name: Build
      run: make
